import { describe, expect, it } from 'vitest'
import {
  buildFilterComplex,
  buildFilterComplexFromConfig,
  computeDelogoRegion,
  resolvePosition,
} from './ffmpegPreview'
import type { EditConfig } from './types'

describe('resolvePosition', () => {
  it('resolves named positions', () => {
    expect(resolvePosition('bottom-right')).toEqual(['W-w-20', 'H-h-20'])
  })

  it('resolves explicit x,y coordinates', () => {
    expect(resolvePosition('40,1600')).toEqual(['40', '1600'])
  })
})

describe('computeDelogoRegion', () => {
  it('converts fractional bounds to pixel x/y/w/h, matching Python int() truncation', () => {
    // Ground truth: editVideos.py::compute_delogo_region(1080, 1920, (0.287, 0.674, 0.694, 0.700))
    expect(computeDelogoRegion('0.287,0.674,0.694,0.700', { width: 1080, height: 1920 })).toEqual({
      x: 309,
      y: 1294,
      w: 439,
      h: 49,
    })
  })
})

// These two ground-truth strings were generated by calling the real
// editVideos.py::build_filter_complex with matching arguments (see the
// implementation commit for the exact Python invocation) -- byte-for-byte
// parity is the whole point of this module.
describe('buildFilterComplex (parity with editVideos.py)', () => {
  it('matches Python output: delogo + blur + explicit watermark/icon coordinates', () => {
    const { filterComplex, outputLabel } = buildFilterComplex(
      {
        canvasSize: '1080x1920',
        background: 'blur',
        watermark: true,
        watermarkPosition: '40,1600',
        watermarkOpacity: 1.0,
        iconPositions: ['900,60'],
      },
      { video: 0, watermark: 1, icons: [2] },
      { x: 310, y: 1295, w: 440, h: 50 },
    )

    expect(filterComplex).toBe(
      '[0:v]delogo=x=310:y=1295:w=440:h=50[clean];' +
        '[clean]split=2[bgsrc][fgsrc];' +
        '[bgsrc]scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,gblur=sigma=20[bg];' +
        '[fgsrc]scale=1080:1920:force_original_aspect_ratio=decrease[fg];' +
        '[bg][fg]overlay=(W-w)/2:(H-h)/2[base0];' +
        '[1:v]format=rgba[wm];' +
        '[base0][wm]overlay=40:1600[base1];' +
        '[base1][2:v]overlay=900:60[outv]',
    )
    expect(outputLabel).toBe('[outv]')
  })

  it('matches Python output: no blur, no delogo, legacy named positions', () => {
    const { filterComplex, outputLabel } = buildFilterComplex(
      {
        canvasSize: '1080x1920',
        background: null,
        watermark: true,
        watermarkPosition: 'bottom-right',
        watermarkOpacity: 1.0,
        iconPositions: ['top-left'],
      },
      { video: 0, watermark: 1, icons: [2] },
    )

    expect(filterComplex).toBe(
      '[0:v]null[base0];' +
        '[1:v]format=rgba[wm];' +
        '[base0][wm]overlay=W-w-20:H-h-20[base1];' +
        '[base1][2:v]overlay=20:20[outv]',
    )
    expect(outputLabel).toBe('[outv]')
  })
})

describe('buildFilterComplexFromConfig', () => {
  const baseConfig: EditConfig = {
    logo_path: 'assets/logo.png',
    icon_path: '',
    watermark_region: '',
    captions_enabled: false,
    background_blur: true,
  }

  it('assigns input indices in video, watermark, icon order', () => {
    const config: EditConfig = { ...baseConfig, icon_path: 'assets/icon.png' }
    const result = buildFilterComplexFromConfig(config, '1080x1920', { width: 1080, height: 1920 })
    expect(result.inputMap).toEqual({ video: 0, watermark: 1, icons: [2] })
  })

  it('turns background_blur off produces no split/blur filters', () => {
    const config: EditConfig = { ...baseConfig, background_blur: false }
    const result = buildFilterComplexFromConfig(config, '1080x1920', { width: 1080, height: 1920 })
    expect(result.filterComplex).not.toContain('gblur')
  })

  it('accepts an explicit {x,y} logo_position dict', () => {
    const config: EditConfig = { ...baseConfig, logo_position: { x: 40, y: 1600 } }
    const result = buildFilterComplexFromConfig(config, '1080x1920', { width: 1080, height: 1920 })
    expect(result.filterComplex).toContain('overlay=40:1600')
  })
})
